name = input("Enter your name :")
theme = input("Enter theme :")
location = input("Enter location :")
day = input("Enter day of week :")
time = input("Enter time :")
verb = input("Enter a verb :")
animal = input("Enter animal :")
bodyPart = input("Enter body part :")
rsvp = input("Enter email :")

print(f"{name} is having a {theme} party on {day}")
print(f"Please make sure to show up at {time}")
print(f"You will be required to {verb} a/an {animal} with your {bodyPart}.")
print(f"RSVP at {rsvp}.")